AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Orders
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: order_id
          AttributeType: S
      KeySchema:
        - AttributeName: order_id
          KeyType: HASH

  OrderApi:
    Type: AWS::Serverless::HttpApi

  OrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.11
      Handler: app.main.handler
      CodeUri: .
      MemorySize: 512
      Timeout: 10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Orders
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref OrderApi

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${OrderApi}.execute-api.${AWS::Region}.amazonaws.com"

  OrderFunctionName:
    Description: Lambda function name
    Value: !Ref OrderFunction

  OrdersTableName:
    Description: DynamoDB table name
    Value: !Ref OrdersTable
